config/routes.rb
Rails.application.routes.draw do
  devise_for :restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    collection do
      get 'search'
    end
  end
  resources :restaurants, only: [:index, :show, :edit, :update]
  resources :drinks, only: [:new, :create, :destroy]
  resources :foods, only: [:new, :create, :destroy]
  resources :sakes, only: [:new, :create, :destroy]
  resources :wines, only: [:new, :create, :destroy] 
  root "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :restaurant

  # def self.ransackable_attributes(auth_object = nil)
  #   %w[name]
  # end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :drinks
  has_many :foods
  has_many :sakes
  has_many :wines

  # def self.ransackable_attributes(auth_object = nil)
  #   %w[name, addres, station]
  # end
end

app/models/sake.rb
class Sake < ApplicationRecord
  belongs_to :restaurant
end

app/models/wine.rb
class Wine < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    edit_restaurant_registration_path(resource)
  end
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :addres, :station, :tel, :comment, :image])
  end

end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

  def new
    @drink = Drink.new
    restaurant = Restaurant.find(current_restaurant.id)
    @drinks = restaurant.drinks
  end

  def create
    @drink = Drink.create(drink_params)
    # drink.jsから送られてきたjson形式のリクエストに対してjson形式でレスポンスをする記述
    # (これによりビューファイルとしてjbuilder(create.json.jbuilder)のデータが返される)
    if @drink.save
      respond_to do |format|
        format.json
      end
    else
      redirect_to action: :new
    end
  end

  def destroy
    @drink = Drink.find(params[:id])
    @drink.destroy
    redirect_to action: :new
  end

  private
  def drink_params
    params.require(:drink).permit(:name, :price, :comment).merge(restaurant_id: current_restaurant.id)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
    restaurant = Restaurant.find(current_restaurant.id)
    @foods = restaurant.foods
  end

  def create
    @food = Food.create(food_params)
    if @food.save
      respond_to do |format|
        format.json
      end
    else
      redirect_to action: :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to action: :new
  end

  private
  def food_params
    params.require(:food).permit(:name, :price, :comment).merge(restaurant_id: current_restaurant.id)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
    @q = Restaurant.all.ransack(params[:q])
    @restaurants = @q.result
  end

  def search
    @search = Restaurant.search(params[:q])
    @restaurants = @search.result
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @drinks = @restaurant.drinks
    @foods = @restaurant.foods
    @sakes = @restaurant.sakes
    @wines = @restaurant.wines
  end

  def edit
  end

  def update
    current_restaurant.update(restaurant_params)
    redirect_to root_path
  end
  
  private
  def  restaurant_params
    params.require(:restaurant).permit(:name, :addres, :station, :tel, :image, :email, :comment)
  end

end

app/controllers/sakes_controller.rb
class SakesController < ApplicationController
  def new
    @sake = Sake.new
    restaurant = Restaurant.find(current_restaurant.id)
    @sakes = restaurant.sakes
  end

  def create
    @sake = Sake.create(sake_params)
    if @sake.save
      respond_to do |format|
        format.json
      end
    else
      redirect_to action: :new
    end
  end

  def destroy
    @sake = Sake.find(params[:id])
    @sake.destroy
    redirect_to action: :new
  end

  private
  def sake_params
    params.require(:sake).permit(:name, :price, :comment, :prefecture).merge(restaurant_id: current_restaurant.id)
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  def new
    @wine = Wine.new
    restaurant = Restaurant.find(current_restaurant.id)
    @wines = restaurant.wines
  end

  def create
    @wine = Wine.create(wine_params)
    if @wine.save
      respond_to do |format|
        format.json
      end
    else
      redirect_to action: :new
    end
  end

  def destroy
    @wine = Wine.find(params[:id])
    @wine.destroy
    redirect_to action: :new
  end

  private
  def wine_params
    params.require(:wine).permit(:name, :price, :comment, :color, :area, :variety).merge(restaurant_id: current_restaurant.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drinks/_index.html.haml
.container-fluid
  .row.bg-primary
    .col
    .font-italic.text-light
      %h4 ドリンクメニュー
    .col
.container-fluid.drink_box
  .row
    .col-1
    .col
      %table.table.table-striped
        %thead
          %tr
            %th{scope: "col", class: "name_width"} 商品名
            %th{scope: "col", class: "price_width"} 価格
            %th{scope: "col", class: "comment_width"} コメント
        %tbody{class: "drink_list"}
          - @drinks.each do |drink|
            %tr
              %td
                = drink.name
              %td
                = drink.price
              %td
                = drink.comment
    .col-1

app/views/drinks/new.html.haml
.container-fluid
  .row.mt-5.text-right
    .col.h5
      = link_to "日本酒リストの編集", new_sake_path, data: {"turbolinks" => false}
    .col-1
    .col.h5
      = link_to "ワインリストの編集", new_wine_path, data: {"turbolinks" => false}
    .col-1
    .col.h5
      %button.btn.btn-success{type: "button"}
        = link_to "店舗ページへ", "/restaurants/#{current_restaurant.id}", class: "text-white"
    .col-1
.container-fluid
  = form_with model: @drink, class: "drink_form", local: true do |f|
    .form-row.mt-5
      .col-1
      .form-group.col-md-3
        %h5 ドリンク名
        = f.text_field :name, class: 'form-control', placeholder: '例：生ビール'
      .form-group.col-md-3
        %h5 価格
        = f.text_field :price, class: 'form-control', placeholder: '例：〇〇〇円'
      .form-group.col-md-4
        %h5 コメント
        = f.text_field :comment, class: 'form-control', placeholder: '例：乾杯に'
      .col-1
    .row.mt-5
      .col.text-center
        = f.submit 'リストを更新する', class: 'btn btn-primary w-25 drink_btn'
.container-fluid.mt-5
.container-fluid
  .row.bg-primary
    .col
    .font-italic.text-light
      %h4 ドリンクメニュー
    .col
.container-fluid.drink_box
  .row
    .col-1
    .col
      %table.table.table-striped
        %thead
          %tr
            %th{scope: "col", class: "name_width"} 商品名
            %th{scope: "col", class: "price_width"} 価格
            %th{scope: "col", class: "comment_width"} コメント
        %tbody{class: "drink_list"}
          - @drinks.each do |drink|
            %tr
              %td
                = drink.name
              %td
                = drink.price
              %td
                = drink.comment
              %td.text-center.delete_box
                -# .delete_btn.remove_list{"data-id" => "${drink.id}"} 削除
                = link_to "削除", drink_path(drink.id), method: :delete, class: "destroy_btn"
    .col-1

app/views/foods/_index.html.haml
.container-fluid
  .row.bg-warning
    .col
    .font-italic.text-light
      %h4 フードメニュー
    .col
.container-fluid
  .row
    .col-1
    .col
      %table.table.table-striped
        %thead
          %tr
            %th{scope: "col", class: "name_width"} 商品名
            %th{scope: "col", class: "price_width"} 価格
            %th{scope: "col", class: "comment_width"} コメント
        %tbody{class: "food_list"}
          - @foods.each do |food|
            %tr
              %td
                = food.name
              %td
                = food.price
              %td
                = food.comment
    .col-1

app/views/foods/create.html.haml
.container-fluid
  .row
    %h2 メニューを更新しました！
.container-fluid
  .row
    %button.btn.btn-success{type: "button"}
      = link_to "店舗ページ", "/restaurants/#{current_restaurant.id}", class: "text-white"

app/views/foods/new.html.haml
.container-fluid
  .row.mt-5.text-right
    .col.h5
      %button.btn.btn-success{type: "button"}
        = link_to "店舗ページへ", "/restaurants/#{current_restaurant.id}", class: "text-white"
    .col-1
.container-fluid
  = form_with model: @food, class: "food_form", local: true do |f|
    .form-row.mt-5
      .col-1
      .form-group.col-md-3
        %h5 フード名
        = f.text_field :name, class: 'form-control', placeholder: '例：枝豆'
      .form-group.col-md-3
        %h5 価格
        = f.text_field :price, class: 'form-control', placeholder: '例：〇〇〇円'
      .form-group.col-md-4
        %h5 コメント
        = f.text_field :comment, class: 'form-control', placeholder: '例：すぐ出る'
      .col-1
    .row.mt-5
      .col.text-center
        = f.submit 'メニューを更新する', class: 'btn btn-primary w-25 food_btn'
.container-fluid.mt-5
.container-fluid
  .row.bg-warning
    .col
    .font-italic.text-light
      %h4 フードメニュー
    .col
.container-fluid.food_box
  .row
    .col-1
    .col
      %table.table.table-striped
        %thead
          %tr
            %th{scope: "col", class: "name_width"} 商品名
            %th{scope: "col", class: "price_width"} 価格
            %th{scope: "col", class: "comment_width"} コメント
        %tbody{class: "food_list"}
          - @foods.each do |food|
            %tr
              %td
                = food.name
              %td
                = food.price
              %td
                = food.comment
              %td.text-center.delete_box
                = link_to "削除", food_path(food.id), method: :delete, class: "destroy_btn"
    .col-1

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CellarSearch
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %body
      = render 'layouts/notifications'
      .container-fluid.sticky-top
        .row.bg-info
          .col-1
          .h2.col-8.text-white
            = link_to "CellarSearch", "/", class: "text-white"
          - if restaurant_signed_in?
            .col-3
              .row.text-justify
                .col.h5
                  = link_to "ログアウト", destroy_restaurant_session_path, method: :delete, class: "text-white"
                .col.h5
                  = link_to "店舗情報編集", edit_restaurant_registration_path(current_restaurant), class: "text-white"
          - else
            .col-3
              .row.text-justify
                .col.h5
                  = link_to "店舗ログイン", new_restaurant_session_path, class: "text-white"
                .col.h5
                  = link_to "新規店舗登録", new_restaurant_registration_path, class: "text-white"
      = yield

app/views/restaurants/index.html.haml
.container-fluid.pt-5.pb-3.main_icon
  .row
    %h1.col.text-center CellarSearch
  .row.mt-3.mb-5
    %p.col.h5.text-center CellarSearchはドリンクメニューから飲食店を探すサービスです。
  .row.d-flex.justify-content-around.mt-5
    %button.btn.btn-success.btn-lg.w-25{type: "button"}
      = link_to "店舗ログイン・新規登録", new_restaurant_session_path, class: "text-white"
.row
  .col-3
  .col-6.text-center.mt-5
    %h1 店舗検索
  .col-3
.container-fluid
  = search_form_for @q, url: search_restaurants_path do |f|
    .row.mb-2.mt-3
      .col-2
      .col
        %h4 ドリンク名
      .col-2
    .row.mb-2
      .col-2
      .col
        = f.search_field :drinks_name_cont, class: 'form-control', placeholder: '例：スーパードライ'
      .col-2
    .row.mt-3
      .col-2
      #accordionExample.accordion.col
        #headingOne
          %button.btn.d-flex.align-items-center{"aria-controls" => "collapseOne", "aria-expanded" => "true", "data-target" => "#collapseOne", "data-toggle" => "collapse", type: "button"}
            %h4 日本酒検索
            %p{class: 'title_btn'}🔽
        #collapseOne.collapse{"aria-labelledby" => "headingOne"}
          .d-flex
            .col.w-50
              銘柄
              = f.search_field :sakes_name_cont, class: 'form-control', placeholder: '例：獺祭'
            .col.w-50
              生産地
              = f.search_field :sakes_prefecture_cont, class: 'form-control', placeholder: '例：山口県'
      .col-2
    .row.mt-3
      .col-2
      #accordionExample.accordion.col
        #headingTwo
          %button.btn.d-flex.align-items-center{"aria-controls" => "collapseTwo", "aria-expanded" => "true", "data-target" => "#collapseTwo", "data-toggle" => "collapse", type: "button"}
            %h4 ワイン検索
            %p{class: 'title_btn'}🔽
        #collapseTwo.collapse{"aria-labelledby" => "headingTwo"}
          .d-flex
            .col.w-50
              名前
              = f.search_field :wines_name_cont, class: 'form-control', placeholder: '例：ロバートモンダヴィ'
            .col.w-50
              生産地
              = f.search_field :wines_area_cont, class: 'form-control', placeholder: '例：アメリカ'
          .d-flex
            .col.w-50
              品種
              = f.search_field :wines_variety_cont, class: 'form-control', placeholder: '例：カベルネ・ソーヴィニヨン'
            .col.w-50
              タイプ
              = f.search_field :wines_color_cont, class: 'form-control', placeholder: '例：赤'
      .col-2
    .row.mt-3
      .col-2
      .col
        %h4 その他条件
    .row.mb-2
      .col-2
      .col
        店名
        = f.search_field :name_cont, class: 'form-control', placeholder: '例：居酒屋◯◯'
      .col-2
    .row.mb-3
      .col-2
      .col-4
        地域
        = f.search_field :addres_cont, class: 'form-control', placeholder: '例：◯◯市'
      .col-4
        最寄駅
        = f.search_field :station_cont, class: 'form-control', placeholder: '例：◯◯駅'
      .col-2
    .row
      .text-right.col.mt-3
        %p ※必要な部分のみ入力してください
        %p ※お探しの商品とその他条件で探すと便利です
      .col-2
    .row.mb-3.d-flex.justify-content-around.mt-3
      .col-6.text-center
        = f.submit '検索', class: 'btn btn-primary search-btn w-25'

app/views/restaurants/search.html.haml
.container-fluid.mt-5
  .row
    .col-1
    .col
      .card.mb-3{style: "max-width: 1080px;"}
        .d-flex.mw-100
          .row.no-gutters.w-100
            - @restaurants.each do |restaurant|
              .col-md-3
                - if restaurant.image.present?
                  .bd-placeholder-img.m-3
                    = image_tag restaurant.image.url, size: "220x180"
              .col-md-8
                .card-body
                  %h4.card-title.d-flex.justify-content-between
                    = restaurant.name
                    = link_to "店舗ページへ", restaurant_path(restaurant.id)
                  %p.card-text
                    .row.d-flex
                      .col
                        = restaurant.addres
                      .col.text-right
                        = restaurant.station
                  %p.card-text
                    = restaurant.tel
                  %p.card-text
                    = restaurant.comment
    .col-1

app/views/restaurants/show.html.haml
.container-fluid.my-5
  .row
    .col-1
    .col
      .card.mb-3{style: "max-width: 1080px;"}
        .d-flex.mw-100
          .row.no-gutters.w-100
            .col-md-3
              - if @restaurant.image.present?
                .bd-placeholder-img.m-3
                  = image_tag @restaurant.image.url, size: "220x180"
            .col-md-8
              .card-body
                %h4.card-title.d-flex.justify-content-between
                  = @restaurant.name
                %p.card-text
                  .row.d-flex
                    .col
                      = @restaurant.addres
                    .col.text-right
                      = @restaurant.station
                %p.card-text
                  = @restaurant.tel
                %p.card-text
                  = @restaurant.comment
- if @foods.present?
  = render "foods/index"
- if @drinks.present?
  = render "drinks/index"
- if @sakes.present?
  = render "sakes/index"
- if @wines.present?
  = render "wines/index"

app/views/sakes/_index.html.haml
.container-fluid
  .row.bg-success
    .col.font-italic.text-light.text-center
      %h4 日本酒リスト
.container-fluid
  .row
    .col-1
    .col
      %table.table.table-striped
        %thead
          %tr
            %th{scope: "col", class: "sake_name"} 商品名
            %th{scope: "col", class: "sake_price"} 価格
            %th{scope: "col", class: "sake_prefecture"} 都道府県
            %th{scope: "col", class: "sake_comment"} コメント
        %tbody{class: "sake_list"}
          - @sakes.each do |sake|
            %tr
              %td
                = sake.name
              %td
                = sake.price
              %td
                = sake.prefecture
              %td
                = sake.comment
    .col-1

app/views/sakes/new.html.haml
.container-fluid
  .row.ml-3.mt-5.text-right
    .col
      %button.btn.btn-success{type: "button"}
        = link_to "店舗ページへ", "/restaurants/#{current_restaurant.id}", class: "text-white"
    .col-1
.container-fluid
  = form_with model: @sake, class: "sake_form", local: true do |f|
    .form-row.mt-5
      .col-1
      .form-group.col-5
        %h5 日本酒銘柄
        = f.text_field :name, class: 'form-control', placeholder: '例：獺祭'
      .form-group.col-5
        %h5 都道府県
        = f.text_field :prefecture, class: 'form-control', placeholder: '例：山口県'
      .col-1
    .form-row.mt-4
      .col-1
      .form-group.col-3
        %h5 価格
        = f.text_field :price, class: 'form-control', placeholder: '例：〇〇〇円'
      .form-group.col-7
        %h5 コメント
        = f.text_field :comment, class: 'form-control', placeholder: '例：純米吟醸'
      .col-1
    .row.mt-5
      .col.text-center
        = f.submit 'リストを更新する', class: 'btn btn-primary w-25 sake_btn'
.container-fluid.mt-5
.container-fluid
  .row.bg-primary
    .col
    .font-italic.text-light
      %h4 日本酒メニュー
    .col
.container-fluid.sake_box
  .row
    .col-1
    .col
      %table.table.table-striped
        %thead
          %tr
            %th{scope: "col", class: "name_width"} 商品名
            %th{scope: "col", class: "price_width"} 価格
            %th{scope: "col", class: "prefecture_width"} 都道府県
            %th{scope: "col", class: "comment_width"} コメント
        %tbody{class: "sake_list"}
          - @sakes.each do |sake|
            %tr
              %td
                = sake.name
              %td
                = sake.price
              %td
                = sake.prefecture
              %td
                = sake.comment
              %td.text-center.delete_box
                = link_to "削除", sake_path(sake.id), method: :delete, class: "destroy_btn"
    .col-1

app/views/wines/_index.html.haml
.container-fluid
  .row.bg-danger
    .col
    .c0l-4.font-italic.text-light
      %h4 ワインリスト
    .col
.container-fluid
  .row
    .col-1
    .col
      %table.table.table-striped
        %thead
          %tr
            %th{scope: "col", class: "wine_name"} 商品名
            %th{scope: "col", class: "wine_price"} 価格
            %th{scope: "col", class: "wine_type"} タイプ
            %th{scope: "col", class: "wine_area"} 生産地
            %th{scope: "col", class: "wine_variety"} 品種
            %th{scope: "col", class: "wine_comment"} コメント
        %tbody{class: "wine_list"}
          - @wines.each do |wine|
            %tr
              %td
                = wine.name
              %td
                = wine.price
              %td
                = wine.color
              %td
                = wine.area
              %td
                = wine.variety
              %td
                = wine.comment
    .col-1

app/views/wines/new.html.haml
.container-fluid
  .row.mt-5.ml-1.text-right
    .col
    %button.btn.btn-success{type: "button"}
      = link_to "店舗ページへ", "/restaurants/#{current_restaurant.id}", class: "text-white"
    .col-1
.container-fluid
  = form_with model: @wine, class: "wine_form", local: true do |f|
    .form-row.mt-5
      .col-1
      .form-group.col-5
        %h5 ワイン名
        = f.text_field :name, class: 'form-control', placeholder: '例：ロバートモンダヴィ'
      .form-group.col-5
        %h5 生産地
        = f.text_field :area, class: 'form-control', placeholder: '例：アメリカ'
      .col-1
    .form-row.mt-4
      .col-1
      .form-group.col-5
        %h5 価格
        = f.text_field :price, class: 'form-control', placeholder: '例：〇〇〇円'
      .form-group.col-5
        %h5 コメント
        = f.text_field :comment, class: 'form-control', placeholder: '例：フルボディ'
      .col-1
    .form-row.mt-4
      .col-1
      .form-group.col-5
        %h5 タイプ
        = f.text_field :color, class: 'form-control', placeholder: '例：赤'
      .form-group.col-5
        %h5 品種
        = f.text_field :variety, class: 'form-control', placeholder: '例：カベルネ・ソーヴィニヨン'
      .col-1
    .row.mt-5
      .col.text-center
        = f.submit 'リストを更新する', class: 'btn btn-primary w-25 wine_btn'
.container-fluid.mt-5
.container-fluid
  .row.bg-warning
    .col
    .font-italic.text-light
      %h4 ワインメニュー
    .col
.container-fluid.wine_box
  .row
    .col-1
    .col
      %table.table.table-striped
        %thead
          %tr
            %th{scope: "col", class: "wine_name"} 商品名
            %th{scope: "col", class: "wine_price"} 価格
            %th{scope: "col", class: "wine_type"} 色
            %th{scope: "col", class: "wine_area"} 生産地
            %th{scope: "col", class: "wine_variety"} 品種
            %th{scope: "col", class: "wine_comment"} コメント
        %tbody{class: "wine_list"}
          - @wines.each do |wine|
            %tr
              %td
                = wine.name
              %td
                = wine.price
              %td
                = wine.color
              %td
                = wine.area
              %td
                = wine.variety
              %td
                = wine.comment
              %td.text-center.delete_box
                = link_to "削除", wine_path(wine.id), method: :delete, class: "destroy_btn"
    .col-1